version: '3'

services:
  web:
    build: .
    command: gunicorn myshop.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code  # Mount the project directory in the container
      - ./data:/code/data  # Persistent volume for SQLite database
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
  
  celery:
    build: .
    command: celery -A myshop worker -l info
    volumes:
      - .:/code  # Ensure Celery has access to your Django code
      - ./data:/code/data  # Persistent volume for SQLite database
    depends_on:
      - web
      - rabbitmq
  
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
